// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFWqycDd1o0MSmrNDtONHJwD_NBsWZFX0',
    appId: '1:937380202117:web:feddc9371f17623cb70bec',
    messagingSenderId: '937380202117',
    projectId: 'sumaq-ia',
    authDomain: 'sumaq-ia.firebaseapp.com',
    storageBucket: 'sumaq-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCknKqCgXvysocosZ1BbpNZiU63uAay6aI',
    appId: '1:937380202117:android:720041beac61a4d8b70bec',
    messagingSenderId: '937380202117',
    projectId: 'sumaq-ia',
    storageBucket: 'sumaq-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzG2tBxt7qvwEGrlokhWz7-uEooTd_8ow',
    appId: '1:937380202117:ios:2586b5274cce5bdfb70bec',
    messagingSenderId: '937380202117',
    projectId: 'sumaq-ia',
    storageBucket: 'sumaq-ia.firebasestorage.app',
    iosClientId:
        '937380202117-rsrv0kdstfm1pg0ohnd6c057lcu4ujcf.apps.googleusercontent.com',
    iosBundleId: 'com.sumaqrutaai.sumaqRutaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzG2tBxt7qvwEGrlokhWz7-uEooTd_8ow',
    appId: '1:937380202117:ios:2586b5274cce5bdfb70bec',
    messagingSenderId: '937380202117',
    projectId: 'sumaq-ia',
    storageBucket: 'sumaq-ia.firebasestorage.app',
    iosClientId:
        '937380202117-rsrv0kdstfm1pg0ohnd6c057lcu4ujcf.apps.googleusercontent.com',
    iosBundleId: 'com.sumaqrutaai.sumaqRutaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFWqycDd1o0MSmrNDtONHJwD_NBsWZFX0',
    appId: '1:937380202117:web:94e0981f4e3bfe06b70bec',
    messagingSenderId: '937380202117',
    projectId: 'sumaq-ia',
    authDomain: 'sumaq-ia.firebaseapp.com',
    storageBucket: 'sumaq-ia.firebasestorage.app',
  );
}
